name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  flutter_sheet_localization:
    path: ../../flutter_sheet_localization

  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.4
  intl: ^0.17.0

dev_dependencies: 
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11

  flutter_sheet_localization_generator:
    path: ../

flutter:
  uses-material-design: true

