name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 5.1.7
homepage: https://github.com/aloisdeniel/flutter_sheet_localization
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  http: ^1.1.0
  meta: ^1.9.1
  csv: ^5.0.2
  recase: ^4.1.0
  code_builder: ^4.5.0
  dart_style: ^2.3.2
  source_gen: ^1.4.0
  build: ^2.4.1
  analyzer: ^6.2.0
  collection: ^1.17.0
  intl: ^0.18.1

  flutter:
    sdk: flutter 

  flutter_sheet_localization: #^5.1.1
    git:
      url: https://github.com/salehahmedZ/flutter_sheet_localization.git
      path: flutter_sheet_localization

  localization_builder: #^0.15.7
    git:
      url: https://github.com/salehahmedZ/flutter_sheet_localization.git
      path: localization_builder


dev_dependencies:
  build_test: ^2.2.0
  build_runner: ^2.4.6