name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 5.1.7
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  http: ^0.13.4
  meta: ^1.7.0
  csv: ^5.0.1
  recase: ^4.0.0
  code_builder: ^4.1.0
  dart_style: ^2.2.3
  source_gen: ^1.2.2

  flutter_sheet_localization: #^5.1.1
    git:
      url: https://github.com/salehahmedZ/flutter_sheet_localization.git
      path: flutter_sheet_localization

  build: ^2.3.0
  analyzer: ^4.1.0
  collection: ^1.16.0
  intl: ^0.17.0

  localization_builder: #^0.15.7
    git:
      url: https://github.com/salehahmedZ/flutter_sheet_localization.git
      path: localization_builder

dev_dependencies:
  build_test: ^2.1.5
  build_runner: ^2.1.11