name: example
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter 
  logging: ^1.0.2
  http: ^0.13.4
  csv: ^5.0.1
  
  template_string: #^0.6.0
    git:
      url: https://github.com/salehahmedZ/flutter_sheet_localization.git
      path: template_string
  
  localization_builder: 
      path: ../